### ISSUE TITLE
the class FOS\RestBundle\Util\Codes is deprecated

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#154]
this class is deprecated.
Instead the Response class (Symfony\Component\HttpFoundation\Response) contains the same constants:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.7/Util/Codes.php
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php

**Comment by Ma27** [comment]
@benbieler could you fix this in the next time?
The 2.x will be released soon: https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/2.0.0-BETA1

**Comment by Ma27** [comment]
updated comment

**Comment by benbieler** [comment]
Ok
