### ISSUE TITLE
use redis caching for validation caching

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#169]

**Comment by Ma27** [comment]
https://github.com/symfony/symfony/pull/12975
https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md#usage

might help (the redis port should be also added in the vagrant/hieradata/common.yaml) and configurable in the app/config/parameters.yml.dist.
the travis-ci/config/parameters.yml should also have that parameter with the value "6379" (default redis port).

**Comment by Ma27** [comment]
@benbieler setting this to pending.
They'll release a new major release supporting symfony 3 and I don't want to be confronted with new deprecations, so we should wait with this until their release :)

**Comment by benbieler** [comment]
Ok, fine
