### ISSUE TITLE
move value objects to keep their package names consistent

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#185]
the following VOs must be moved and renamed:

**AppBundle\Model\Ip\IpLocation** => **AppBundle\Model\Ip\Value\IpLocation**
**AppBundle\Model\User\Registration\Value\Result** => **AppBundle\Model\User\Value\Registration**

**Comment by Ma27** [comment]
@benbieler could you please fix this in the next time as I'd love to see a clean directory structure :)

**Comment by benbieler** [comment]
@ma27 Sure, I can do this tomorrow😉

**Comment by Ma27** [comment]
thanks :+1:
