### ISSUE TITLE
enhance contribution guidelines

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#214]
The current approach described in the CONTRIBUTING.md and the usage of waffle.io is quite awesome and provides an easy and powerful workflow. There's just one case where it doesn't fit its needs:

Imagine a story describing one feature. Any ticket should have an assignee and all resulting commits **must** be squashed before merging in order to avoid a big history with much commits like "fixed type (again)...".

When having stories this causes too large diffs with a non-reliable blame feature.

Therefore I'd like to propose a change in the contribution guidelines for stories:

In case of a story the ticket **MUST** not have an assignee. The "real" stories are just comming and it is quite impossible to have just one working on it.
In case of a story the commits should **NOT** be squashed. As a story contains a lot of sub-tasks written in the PR of the story. (when having ten "minor review fixes" commits, they should be squashed, but not sub-tasks").

When having the following tasks: 'import deps for $feature', 'build api and socket connector for $feature', 'implement frontend based on reactjs for $feature', 'use server-side rendering for $feature' then the story should have a commit for each of those subtasks squashed.

The repo owner (in this case "me") should squash and merge story PRs after a big review properly to fulfill the provided rules.

Every story **MUST** have at least two reviewers (most of the tickets are not that heavy, so one reviewer is enough, but stories introduce great changes, so two reviewers are necessary)

**Comment by Ma27** [comment]
@benbieler if you agree with that proposal, I'll change the CONTRIBUTING.md and all further stories can be fixed in that way.

**Comment by benbieler** [comment]
:+1:

**Comment by Ma27** [comment]
ok.
There's still one scenario where I'm unsure. Imagine the following case:

We have the following sub-tasks given in our PR (you know those checkboxes):

```
'import deps for $feature'
'build api and socket connector for $feature'
'implement frontend based on reactjs for $feature'
'use server-side rendering for $feature'
```

What if the history of the feature branch looks like this:

```
import deps (Author: Ben Bieler)
basic implementation of a socket connector (Author: Maximilian Bosch)
fix version constraint for dep $dep (Author: Ben Bieler, relates to task 1)
# more commits of the feature
```

In this case we'll cannot squash as the order is invalid (between the two commits is the commit for task 2.
Any ideas @benbieler ? I'll think about it and post it tomorrow if I get an idea.

**Comment by Ma27** [comment]
@benbieler could you please write this down into the contributing.md?
