### ISSUE TITLE
avoid data loss when changing page

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#234]
### Description

When switching between routes, react re-renders the children which causes data loss as the data will never be stored.
### Steps to reproduce

Just enter something in a form and switch to another page and back.
### Expected behavior

A warning should be displayed that the user is about to leave the page and data will be lost, but maybe a flux-based solution to store such data in certain containers might help ( @benbieler what do you think about the second idea?)
### Related issues

none

**Comment by benbieler** [comment]
Well I think that the data should be stored. A notification is to basic. How about localstorage? Just encode the data as a json object, and parse it when revisiting the page?

**Comment by Ma27** [comment]
:+1: good idea!
How about a `LocalStorageMemoryStore` which stores data and renders them into the pages.

The only thing is that we have to implement a proper cleanup strategy in order to avoid unnecessary dumped data in the storage of  a user.

But should we only store stuff like form data using that approach or also other data like posts when implementing the actual feature?

**Comment by benbieler** [comment]
I think form data will do (Github is a good example)...

**Comment by Ma27** [comment]
:+1:

**Comment by Ma27** [comment]
can be closed actually. In #258 I've created an approach to fetch store data directly at component's mount, so nothing will be lost
