### ISSUE TITLE
refactor frontend testing aliases

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#235]
when having multiple internal `form` components, they don't conflict due to mocha's internal behavior, but having multiple tests with the same name is not very clean.

**Comment by Ma27** [comment]
i'd suggest the following:

``` javascript
// before
describe('Form', () => {
});

// after
describe('components::section::feature::Form', () => {

});
```

**Comment by Ma27** [comment]
@benbieler this is IMHO something that can be done during #353, so I'll close this for now.

**Comment by benbieler** [comment]
Jup. Fine

**Comment by benbieler** [comment]
Task created
