### ISSUE TITLE
refactor webpack configuration

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#238]
while symfony commands throw errors when adjusting invalid CLI options, webpack is quite liberal and accepts them although it doesn't know what to do.
This can be used to add custom config options to tell webpack whether to create a dev or prod bundle.

**Comment by Ma27** [comment]
can be solved via `process.env.NODE_ENV`

**Comment by benbieler** [comment]
@Ma27 That will only work on ubuntu. On windows you will have to do the following: 
`set NODE_ENV=production`

**Comment by Ma27** [comment]
yes, thanks for your feedback, but that's exactly what I'm planning to do.
I'll use this ENV var and provide a fallback if someone runs the stuff on a local environment (in vagrant the parameter will be configurable).

I'll just fetch the parameter and the configuration in a local environment is something a contributor is responsible for, we don't have to handle this. And please note that I won't care about Windows issues (if it works fine in the VM, tickets can be fixed).
There's already a lot stuff (like our redis handling or large parts of the installer) which doesn't work properly with windows.

**Comment by benbieler** [comment]
Ok, sounds great!
