### ISSUE TITLE
JMSDiExtraBundle vs XML

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#24]
we should decide whether to use the JMSDiExtraBundle or plain xml for service configurations.
The advantage of the JMSDiExtraBundle is that we don't need any symfony2 extension and can handle all the DI stuff inside our PHP code: http://jmsyst.com/bundles/JMSDiExtraBundle

@benbieler what do you think??

**Comment by benbieler** [comment]
As I'm generally not a big fan of XML I'd tend to use the JMSDiExtraBundle

**Comment by Ma27** [comment]
ok :)
I've just decided to use annotations for the models, too, so the xml will be used for translations only (as there's no annotation support) and we don't have any DI extension and unnecessary boilerplate code.

**Comment by Ma27** [comment]
@benbieler I really regret that decision :D
/related to #143
