### ISSUE TITLE
Vagrant Network File System mounting problem

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#243]
### Description

When I `sudo vagrant up` the box, the booting fails at the following spot: 

``` ruby
  config.vm.synced_folder '.', '/var/www/sententiaregum', :nfs => true, :mount_options => ['dmode=777','fmode=777','uid=33','gid=33']
```

(https://github.com/Sententiaregum/Sententiaregum/blob/master/Vagrantfile#L12)
### Steps to reproduce

`sudo vagrant up`
### Solution:

I just had to change the command to the following in order to run the box: 

``` ruby
  config.vm.synced_folder '.', '/var/www/sententiaregum', :nfs => {:mount_options => ['dmode=777','fmode=777','uid=33','gid=33']}
```

**Comment by Ma27** [comment]
those `mount_options` were a hack for some nodejs issue when mounting stuff into a machine.
My recommendation would be to remove those options and change the line to this:

``` ruby
config.vm.synched_folder '.', '/var/www/sententiaregum', :nfs => true
```

ANd that's it. After this it should be tested how it works and then we can finally fix that hack :)

**Comment by benbieler** [comment]
![reaction-reactiongifs-wrestling-12WZ4dHjXBMUms](https://camo.githubusercontent.com/79e5ca091f47fa54a3d4bc8936fdbbe4dc009d90/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f3132575a3464486a58424d556d732f67697068792e676966)

@Ma27 I love this new feature :laughing:

**Comment by Ma27** [comment]
ok let's use this GIF instead of github reactions ;)

**Comment by Ma27** [comment]
removing question and discuss label as we've provided a way to solve this and there's nothing to discuss

**Comment by Ma27** [comment]
should use ubuntu 16.04 as this is the latest LTS
