### ISSUE TITLE
use pnpm

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#245]
don't need a description, just look at this: https://github.com/npm/npm/issues/11283

`PNPM` could be used to speedup the npm install process

**Comment by benbieler** [comment]
:D Crazy...

**Comment by benbieler** [comment]
or just use pnpm: https://github.com/rstacruz/pnpm

**Comment by Ma27** [comment]
ok :)
renaming the issue title

**Comment by Ma27** [comment]
after the funny experiences with pnpm of today I think we should think about this again

**Comment by benbieler** [comment]
![fail-car-crash-YvsN4ZhnXn38I](https://camo.githubusercontent.com/5268203c39bebe650249d3f384e32d0ea69648e8/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f5976734e345a686e586e3338492f67697068792e676966)

**Comment by Ma27** [comment]
yeah, that GIF explains quite well what happened today when trying to use `PNPM` :D

**Comment by Ma27** [comment]
closing this as won't fix.
The progress bar thing can be fixed when using `2.0` of https://github.com/willdurand/puppet-nodejs

We're planning to support npm configs for certain reasons like explained here (https://github.com/willdurand/puppet-nodejs/issues/138 or https://github.com/willdurand/puppet-nodejs/issues/143)
