### ISSUE TITLE
Repair preinstall handler

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#249]
### Description

The preinstall handler should create the doctrine schema properly.
### Steps to reproduce
- Purge DB & run `composer install`
### Expected behavior

The schema should be setup properly

**Comment by Ma27** [comment]
This is how it feels to work with that:
![cat-fai-mKmFi3M6zTVAI](https://camo.githubusercontent.com/65069742bcb5d890acc596960e6a754ca2c28a7b/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6d4b6d4669334d367a545641492f67697068792e676966)

yes, you're right, the PreInstall stuff is just a bad and poorly implemented hack.

I'd suggest creating a "DoctrineDevSetupCommand" which solves the doctrine stuff properly

**Comment by Ma27** [comment]
during the progress of this issue the behavior of the `capistrano` deploy strategy must be asserted

**Comment by Ma27** [comment]
during this improvement we should move all the dev stuff (babel, webpack) to the `dev` section and build a rule in the install handler that the NPM stuff will be executed during the dev mode only (in case of prod, the bundles should be deployed)
