### ISSUE TITLE
New loading spinner

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#250]
### Description

A better loading spinner would be nice.
### Steps to reproduce
- Register

**Comment by Ma27** [comment]
![ncis-la-deeks-kensi-A0wgqZOaGtDZC](https://camo.githubusercontent.com/b809a7bb4f27ae1d842c8a620e76eff44b297c3b/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f41307767715a4f614774445a432f67697068792e676966)

**Comment by benbieler** [comment]
![donald-fJPCtDrNvZdM4](https://camo.githubusercontent.com/0bf4c262cf315e04c112a7c19475df5ce877eae6/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f664a50437444724e765a644d342f67697068792e676966)
