### ISSUE TITLE
find out what went wrong in the LoadableButtonBar

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#253]
## Description

@benbieler observed a very interesting bug in your mocha-babel testsuite in the component `LoadableButtonBar`: it threw an exception all the time (even when using `React.createElement` in favor of JSX). When using a lowercase name (`spinner` instead of `Spinner` it worked).

See #250 and #251 for further information
### Steps to reproduce

Rename the variable `spinner` in the `LoadatbleButtonBar.js` to `Spinner`.
### Expected behavior

The test should be green.

**Comment by Ma27** [comment]
@benbieler I've assigned that to you as you were the author of the newly introduced code where that bug could be observed. When I'm done with #35 and have more free time available, I may have a look on it, too :)

**Comment by benbieler** [comment]
@Ma27: Well in react you usually use the lower case declaration to render Html tags. Components are upper-cased.

See: https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components

But this still does not make any sense. I came to the conclusion that something with the react-spinkit package has to be malfunctioning. It might though have something to do with the fact that they are using  coffee instead of regular JS.

**Comment by Ma27** [comment]
OK, thanks for your investigation.
https://github.com/KyleAMathews/react-spinkit/blob/master/README.md according to their docs it "should" work.

If we don't find a solution here, please open a ticket in their repository :)

**Comment by benbieler** [comment]
@Ma27  [Done](https://github.com/KyleAMathews/react-spinkit/issues/31)

**Comment by Ma27** [comment]
will be fixed in #258 .
The issue was not related to the uppercase/lowercase behavior which was just an odd side-effect of the JSX implementation of BabelJS (lowercase is detected as native component), but the component included css using the `require` function.
Webpack which bundled all of this into certain output files is able to handle this properly due to its internal loader implementation and the independent code generator which dumps the whole loaded code into certain build files. In Mocha the issue came across since the v8 engine is unable to handle css files properly. Using the `ignore-styles` NPM module in `mocha` test runs fixes this issue for mocha, too.
