### ISSUE TITLE
investigate es6 features and pure node 6 compat

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#263]
### Description

nodejs 6 has been released some days ago and supports most of the ES6 features declared in the ECMA spec. Unfortunatly all of our frontend tests are quite slow due to the fact that we have to use babel in order to translpile the code properly.

**Comment by Ma27** [comment]
@benbieler although our test suite is not "too fast" I think, we should close that as babel verifies that we only use code which is known to babel and can be transpiled by babel.
If we introduce some kind of ES7-edge-case-features and simply check the tests, it might lead to regression issues building the JS bundle.

**Comment by benbieler** [comment]
ok

**Comment by Ma27** [comment]
closing for now. If some requirements change or `babel` introduces some features that could help us here, we can reopen this.
