### ISSUE TITLE
make basic box params configurable

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#271]
### Description

the box parameters should be configurable:
currently the vagrant config uses a simple and sensible configuration (one CPU, 1GB RAM) and contributors with powerful machines should be able to use more powerful VMs (e.g. increasing the memory would help to avoid memory leaks in composer processes).
The IP should be configurable in order to avoid collisions in the private network.

/cc @benbieler do you know more parameters that should be mutable?

**Comment by benbieler** [comment]
@Ma27 I think that it would be quite usefull to be able to change the box name.

**Comment by Ma27** [comment]
@benbieler well there are a lot of boxes out there (e.g. for windows or bsd based systems) that cannot be supported.
Currently I'm facing a lot vagrant issues (see #243 , #268 , #238 (webpack issues in vagrant)) and I have to find solutions for certain issues. After this we can conitnue talking about configurable box names, ok?

**Comment by benbieler** [comment]
@Ma27 Fine. I actually ment the following: Sententiaregum VM -> e.g. : SVM

**Comment by Ma27** [comment]
ok, yes - why not (if one VM fails completly or you'd like to orchestrate multiple VMs for certain forks).

**Comment by benbieler** [comment]
yep
