### ISSUE TITLE
create custom bundle exceptions instead of global spl exception

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#30]
AppBundle\Exception\RuntimeException Im favor of \RuntimeException.
The JMSCommandBundle will help in that case

**Comment by Ma27** [comment]
http://jmsyst.com/bundles/JMSCommandBundle%20
when using the "exceptionify" command, the job can be done very simple

**Comment by benbieler** [comment]
Due to the bad code quality, and awful support, we won't fix this issue.

**Comment by Ma27** [comment]
I should note that he means the awful support of the JMSCommandBundle which we wanted to use for this and not our support ;)
/cc @benbieler
