### ISSUE TITLE
improve issue labels

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#303]
1.: it should be iterated over all issues and they should have more detailed labels to gain more information (we need green labels for `Model`, `API`, `React` and `Application Layer` (=symfony/doctrine)

2.: we should think about using a more detailed milestone scheme (0.x dev releases to add more and more features and fixes and the work is better trackable as throwing everything into a `1.0` milestone might look confusing)

3.: we should have a look at the contribution guidelines and evaluate whether some more things there can be improved.

4.: prefix all waffle.io related labels (`Status: In Progress`, `Status: Needs Merge`)

5.: `Infrastructure` should be a yellow label (`Bug`, `Story`, `Security`, `Enhancement`, `Improvement`, `Code Quality`, `Documentation`, `Refactor` should be the only status labels, `Bug` and `Security` shuold have another color).

The other labels should be (re)moved, but the old commits should be kept...

**Comment by Ma27** [comment]
@benbieler WDYT??

**Comment by benbieler** [comment]
@Ma27  Seems fine to me

**Comment by Ma27** [comment]
ok, then I'll do this when I'm done with the PR :)

**Comment by Ma27** [comment]
done...
