### ISSUE TITLE
resolve race conditions

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#307]
### Description

it seems as `moxios.wait` introduces a heavy race condition which fails from time to time when exeucing the whole test suite:
https://travis-ci.org/Sententiaregum/Sententiaregum/builds/140234855
### Steps to reproduce
- run `npm test`

**NOTE:** please keep in mind that it's only from time to time reproducable
### Expected behavior

the test passes.
We could write something like this:

``` javascript
it('requests credentials', () => {
  // all the preparation stuff

  poll(() => {
    // all the assertions
  });
});
```

The whole moxios stuff could be done inside and the `poll` API blocks until the assertions are done.

**Comment by Ma27** [comment]
just had a look at the test suite. Although it seems to do its job now in travis, all assertions are totally fragile due to those race conditions. /cc @benbieler

**Comment by benbieler** [comment]
ok @Ma27

**Comment by Ma27** [comment]
replaced by #338
