### ISSUE TITLE
make nfs usage optional

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#325]
due to integrative issues between the host and the NFS it sometimes is difficult/risky to use NFS in the developer VM. THerefore it might be better to make this optional.

**Comment by Ma27** [comment]
moving to 0.3 as that's a change that might be done somehow in the future and everything which is not a core feature, but needs to be added before stabilization, should be moved to 0.3.

**Comment by benbieler** [comment]
Sounds good.

**Comment by Ma27** [comment]
moving to 0.1 again (`vagrant + nfs` seems to be incompatible with nixos).
see e.g. https://github.com/mitchellh/vagrant/blob/ea43d693431080c145467ea16cf9f955413b1211/plugins/hosts/linux/cap/nfs.rb#L22
