### ISSUE TITLE
consider removing PHPCS

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#339]
### Description

According to the support of StyleCI they aren't fully compliant with the rules of PHPCS. There were issues like #309 that caused a pain to fix. Furthermore there are more plans of PHPCS to build custom rules that could cause more pain in the future.

Thefore the following suggestion:
- Our CS is quite well now due to many linters, so a StyleCI which simply tells people in PRs to keep their style clean is enough
- If some broken code exists due to changing rules for instance, StyleCI might generate a PR

**Comment by Ma27** [comment]
@benbieler WDYT about that?

**Comment by benbieler** [comment]
@Ma27 Yeah, sounds like a plan...
