### ISSUE TITLE
Use npm-precommit

### ISSUE THREAD

**Issue by benbieler** [Sententiaregum/Sententiaregum#345]
https://github.com/observing/pre-commit

**Comment by benbieler** [comment]
@Ma27 Whats your take on this?

**Comment by Ma27** [comment]
well, I don't think that we need a pre-commit to run our tests as the only way how to push to master is opening and merging a PR and this PR can't be merged unless the tests pass.

One idea we could work on (if you'd like to take it as one of the next tasks after reCAPTCHA, go for it :+1: ) might be a commit message validator which validates how the commit message should look like.

**Comment by benbieler** [comment]
Ok, then. I just thought that it might be usefull since you would no longer have all of these style related micro commits... -> recaplcha...

**Comment by Ma27** [comment]
ok. Can talk about the commit validator I've proposed when we're done with all the work related to `0.1` @benbieler

**Comment by benbieler** [comment]
@Ma27 Ok. Good.
