### ISSUE TITLE
create packagist repository

### ISSUE THREAD

**Issue by Ma27** [Sententiaregum/Sententiaregum#42]
a packagist repo can be helpful when using "composer create-project" (update readme.md)
we need an author section inside composer.json that gives information about the core developers of that project.

**Comment by benbieler** [comment]
https://packagist.org/packages/sententiaregum/

**Comment by Ma27** [comment]
thank you @benbieler 
could you please open a PR your commit?

and could you please add some packagist badges to the readme.md: https://poser.pugx.org/

**Comment by Ma27** [comment]
ah and your commit breaks the test suite
